/**
 * Central routing configuration for Kasi
 * Single source of truth for all routes, specs, metadata, and status.
 */

export interface RouteConfig {
  path: string;
  name: string;
  specSectionId?: string;
  status: 'built' | 'stub' | 'external';
  metaTitle: string;
  metaDescription: string;
  h1: string;
  sub: string;
  isNav?: boolean;
}

export const ROUTES: Record<string, RouteConfig> = {
  HOME: {
    path: '/',
    name: 'Home',
    specSectionId: '02',
    status: 'built',
    metaTitle: 'Kasi | Automate your DMs. Answer every WhatsApp & Instagram DM.',
    metaDescription: 'Kasi is the social commerce operating system that answers every customer, negotiates, takes payment, and manages fulfilment.',
    h1: 'Automate your DMs. Answer every WhatsApp, Instagram and Telegram DM.',
    sub: 'Kasi is the operating system for businesses that sell on WhatsApp and Instagram.',
    isNav: true,
  },
  HOW_IT_WORKS: {
    path: '/how-it-works',
    name: 'How it works',
    specSectionId: '03',
    status: 'stub',
    metaTitle: 'How Kasi Works | Demo & Interactive Order Walkthrough',
    metaDescription: 'Watch Kasi take a customer from first message to paid and out for delivery.',
    h1: 'See a real order happen, start to finish.',
    sub: 'No slides. Watch Kasi take a customer from first message to paid and out for delivery, then try it yourself.',
    isNav: true,
  },
  FEATURES: {
    path: '/features',
    name: 'Features Hub',
    specSectionId: '04',
    status: 'stub',
    metaTitle: 'Kasi Features | The Complete Social Commerce Operating System',
    metaDescription: 'Explore the full suite of Kasi capabilities: Sales Engine, Fulfilment, Payments, and CRM.',
    h1: 'Everything Kasi does, under the hood.',
    sub: 'From autonomous negotiation to rider dispatch, explore each part of your social commerce operating system.',
    isNav: true,
  },
  FEATURE_SALES: {
    path: '/features/sales-engine',
    name: 'Sales Engine',
    specSectionId: '05',
    status: 'stub',
    metaTitle: 'Sales Engine | Autonomous DM Negotiation & Sales',
    metaDescription: 'Answers in seconds, negotiates within your margins, and closes the order inside WhatsApp and Instagram.',
    h1: 'An AI sales agent that actually closes.',
    sub: 'Answers in seconds, negotiates within your margins, and collects payments in the chat.',
  },
  FEATURE_FULFILMENT: {
    path: '/features/fulfilment',
    name: 'Fulfilment Center',
    specSectionId: '06',
    status: 'stub',
    metaTitle: 'Fulfilment Center | Order Queue & Dispatch Management',
    metaDescription: 'Paid orders drop into one unified list for packing, dispatch, and automatic status updates.',
    h1: 'From paid DM to dispatched rider in minutes.',
    sub: 'Every confirmed order lands in one clear queue. Pack, dispatch, and notify automatically.',
  },
  FEATURE_DELIVERY: {
    path: '/features/delivery',
    name: 'Delivery & Pricing',
    specSectionId: '07',
    status: 'stub',
    metaTitle: 'Delivery & Pricing | Automated Rider Coordination & Fee Calc',
    metaDescription: 'Dynamic delivery fee calculations and parallel dispatch notifications to your trusted riders.',
    h1: 'Automated logistics and delivery calculations.',
    sub: 'Calculate delivery fees on the fly and broadcast orders to your saved dispatch riders in parallel.',
  },
  FEATURE_PAYMENTS: {
    path: '/features/payments',
    name: 'Payments & Checkout',
    specSectionId: '08',
    status: 'stub',
    metaTitle: 'Payments & Checkout | Direct Paystack In-Chat Checkout',
    metaDescription: 'Instant payment verification and automated receipts without sending screenshots or account numbers.',
    h1: 'Collect payments directly inside the conversation.',
    sub: 'Instant Paystack verification, automated receipts, and zero manual screenshot confirmations.',
  },
  FEATURE_CHATS: {
    path: '/features/chats',
    name: 'Chats & Control',
    specSectionId: '09',
    status: 'stub',
    metaTitle: 'Chats & Control | Live Conversation Oversight & Human Handoff',
    metaDescription: 'Real-time DM oversight. Step into any conversation with one line or take over seamlessly.',
    h1: 'Total visibility. Step in whenever you want.',
    sub: 'Watch live conversations across WhatsApp and Instagram. Instruct Kasi with one line or take over seamlessly.',
  },
  FEATURE_CUSTOMERS: {
    path: '/features/customers',
    name: 'Customers & CRM',
    specSectionId: '10',
    status: 'stub',
    metaTitle: 'Customers & CRM | Automatic Customer Profiles & Order History',
    metaDescription: 'Every DM automatically saves a customer profile, order history, and re-engagement tags.',
    h1: 'Turn every chatter into a repeat buyer.',
    sub: 'Every conversation creates a rich customer profile with order history, lifetime value, and smart tags.',
  },
  FEATURE_ANALYTICS: {
    path: '/features/analytics',
    name: 'Analytics & Bookings',
    specSectionId: '11',
    status: 'stub',
    metaTitle: 'Analytics & Bookings | Actionable Revenue & Appointment Metrics',
    metaDescription: 'Clear sales charts, inventory metrics, and automated appointment scheduling.',
    h1: 'Clarity on your cash, orders, and customer demand.',
    sub: 'Real-time metrics on conversion rates, revenue, top products, and scheduled appointments.',
  },
  PLATFORMS: {
    path: '/platforms',
    name: 'Platforms & Integrations',
    specSectionId: '12',
    status: 'stub',
    metaTitle: 'Platforms & Integrations | WhatsApp, Instagram, Messenger & Telegram',
    metaDescription: 'Connect WhatsApp, Instagram DMs, Facebook Messenger, and Telegram to a unified commerce engine.',
    h1: 'One AI brain across every channel you sell on.',
    sub: 'Connect WhatsApp, Instagram, Messenger, and Telegram to a unified commerce engine.',
  },
  TRY: {
    path: '/try',
    name: 'Try it',
    specSectionId: '13',
    status: 'stub',
    metaTitle: 'Try Kasi Yourself | Interactive Customer Experience Demo',
    metaDescription: 'Test Kasi in real-time as a buyer on WhatsApp and see how smoothly it sells.',
    h1: 'Experience Kasi as a customer right now.',
    sub: 'Chat with our live demo store on WhatsApp and see how quickly Kasi answers, negotiates, and checks out.',
    isNav: true,
  },
  MARKET: {
    path: '/market',
    name: 'Market',
    specSectionId: '14',
    status: 'built',
    metaTitle: 'Kasi Market | Discover & Buy from Local Nigerian Retailers',
    metaDescription: 'Shop verified local vendors directly on WhatsApp.',
    h1: 'Shop directly with top social commerce vendors.',
    sub: 'Kasi Market connects you directly with verified sellers.',
    isNav: true,
  },
  PRICING: {
    path: '/pricing',
    name: 'Pricing',
    specSectionId: '15',
    status: 'stub',
    metaTitle: 'Pricing | Simple Flat Monthly Plans for Social Commerce Sellers',
    metaDescription: 'Transparent pricing with no commissions on your sales. Starting from ₦18,000/month.',
    h1: 'Simple, transparent pricing for growing sellers.',
    sub: 'No hidden cuts. Keep 100% of your sales with flat monthly plans built for Nigerian SMEs.',
    isNav: true,
  },
  ABOUT: {
    path: '/about',
    name: 'About Endogenous',
    specSectionId: '16',
    status: 'stub',
    metaTitle: 'About Endogenous Tech | Building Africa’s Social Commerce OS',
    metaDescription: 'Learn about our mission to power the millions of merchants running on social DMs.',
    h1: 'We build technology for the merchants running Africa’s social economy.',
    sub: 'Endogenous Technologies empowers informal and growing retailers with autonomous sales infrastructure.',
  },
  BLOG: {
    path: 'https://blog.usekasi.com',
    name: 'Blog',
    specSectionId: '17',
    status: 'external',
    metaTitle: 'Kasi Blog | Playbooks & Guides for Social Sellers',
    metaDescription: 'Strategies, product updates, and growth stories for social commerce merchants.',
    h1: 'Playbooks and insights for social commerce.',
    sub: 'Tactics and stories from the fastest-growing stores on WhatsApp and Instagram.',
  },
  CONTACT: {
    path: '/contact',
    name: 'Contact',
    specSectionId: '18',
    status: 'stub',
    metaTitle: 'Contact Kasi | Talk to Our Sales & Support Team in Lagos',
    metaDescription: 'Get in touch with our engineering and growth team in Lagos, Nigeria.',
    h1: 'Let’s talk about growing your social sales.',
    sub: 'Our team in Lagos is ready to help you set up Kasi, connect your channels, and train your AI rep.',
  },
  GET_STARTED: {
    path: '/get-started',
    name: 'Get Started',
    specSectionId: '01',
    status: 'built',
    metaTitle: 'Get Started with Kasi | Free Account Setup',
    metaDescription: 'Sign up in two minutes and connect your WhatsApp store.',
    h1: 'Start selling autonomously today.',
    sub: 'Connect your store and start answering every message in seconds.',
  },
  DEV_LOGOS: {
    path: '/dev/logos',
    name: 'Vector Assets Dev Tool',
    status: 'built',
    metaTitle: 'Dev: Logo Assets Inspector',
    metaDescription: 'Verified vector inspection route for internal development.',
    h1: 'Verified Vector Assets Test Suite',
    sub: 'Internal inspector for brand and partner SVGs.',
  },
};
