/**
 * Central routing configuration for Kasi
 * Single source of truth for all routes, specs, metadata, and status.
 */

export interface RouteConfig {
  path: string;
  name: string;
  specSectionId?: string;
  status: 'built' | 'stub' | 'external';
  metaTitle: string;
  metaDescription: string;
  h1: string;
  sub: string;
  isNav?: boolean;
}

export const ROUTES: Record<string, RouteConfig> = {
  HOME: {
    path: '/',
    name: 'Home',
    specSectionId: '02',
    status: 'built',
    metaTitle: 'Kasi | Automate your DMs. Answer every WhatsApp & Instagram DM.',
    metaDescription: 'Kasi is the social commerce operating system that answers every customer, negotiates, takes payment, and manages fulfilment.',
    h1: 'Automate your DMs. Answer every WhatsApp, Instagram and Telegram DM.',
    sub: 'Kasi is the operating system for businesses that sell on WhatsApp and Instagram.',
    isNav: true,
  },
  HOW_IT_WORKS: {
    path: '/how-it-works',
    name: 'How it works',
    specSectionId: '03',
    status: 'built',
    metaTitle: 'How Kasi Works | Demo & Interactive Order Walkthrough',
    metaDescription: 'Watch Kasi take a customer from first message to paid and out for delivery.',
    h1: 'See a real order happen, start to finish.',
    sub: 'No slides. Watch Kasi take a customer from first message to paid and out for delivery, then try it yourself.',
    isNav: true,
  },
  FEATURES: {
    path: '/features',
    name: 'Features Hub',
    specSectionId: '04',
    status: 'built',
    metaTitle: 'Kasi Features | The Complete Social Commerce Operating System',
    metaDescription: 'Explore the full suite of Kasi capabilities: Sales Engine, Fulfilment, Payments, and CRM.',
    h1: 'Everything Kasi does, in one place.',
    sub: 'Kasi is not a chatbot bolted onto your shop. It is the system your shop runs on. Here is every part of it.',
    isNav: true,
  },
  FEATURE_SALES: {
    path: '/features/sales-engine',
    name: 'Sales Engine',
    specSectionId: '05',
    status: 'built',
    metaTitle: 'Sales Engine | Autonomous DM Negotiation & Sales',
    metaDescription: 'Answers in seconds, negotiates within your margins, and closes the order inside WhatsApp and Instagram.',
    h1: 'A salesperson who never sleeps, never forgets, and never goes off-script.',
    sub: 'The Sales Engine is the brain behind every Kasi chat. It greets, recommends, negotiates inside the limits you set, and closes the order with payment taken. In your voice, at your prices.',
  },
  FEATURE_FULFILMENT: {
    path: '/features/fulfilment',
    name: 'Fulfilment Center',
    specSectionId: '06',
    status: 'built',
    metaTitle: 'Fulfilment Center | Order Queue & Dispatch Management',
    metaDescription: 'Paid orders drop into one unified list for packing, dispatch, and automatic status updates.',
    h1: 'Every paid order, one list, one next move.',
    sub: 'No spreadsheets, no "which order was this again?" Kasi lines up every paid order and tells you the single next thing to do. Tap it. The customer gets told. Move on.',
  },
  FEATURE_DELIVERY: {
    path: '/features/delivery',
    name: 'Delivery & Pricing',
    specSectionId: '07',
    status: 'built',
    metaTitle: 'Delivery & Pricing | Automated Rider Coordination & Fee Calc',
    metaDescription: 'Dynamic delivery fee calculations and parallel dispatch notifications to your trusted riders.',
    h1: 'The right delivery fee, before they pay. Every time.',
    sub: 'Kasi asks for the customer\'s live location and a written description, works out the distance, and adds a fair fee to checkout. No guessing, no losses, no "the rider says it\'s more."',
  },
  FEATURE_PAYMENTS: {
    path: '/features/payments',
    name: 'Payments & Checkout',
    specSectionId: '08',
    status: 'built',
    metaTitle: 'Payments & Checkout | Direct Paystack In-Chat Checkout',
    metaDescription: 'Instant payment verification and automated receipts without sending screenshots or account numbers.',
    h1: 'Paid means paid. Kasi knows the moment it happens.',
    sub: 'Kasi sends a secure Paystack checkout, and the instant payment clears it confirms to the customer and moves the order forward. No manual checking, no fake "I\'ve paid" screenshots slipping through.',
  },
  FEATURE_CHATS: {
    path: '/features/chats',
    name: 'Chats & Control',
    specSectionId: '09',
    status: 'built',
    metaTitle: 'Chats & Control | Live Conversation Oversight & Human Handoff',
    metaDescription: 'Real-time DM oversight. Step into any conversation with one line or take over seamlessly.',
    h1: 'Hands-off, but never in the dark.',
    sub: 'Watch every chat as it happens, read a one-line AI summary of where each one is, and step in with a single instruction. Kasi runs the floor; you stay the owner.',
  },
  FEATURE_CUSTOMERS: {
    path: '/features/customers',
    name: 'Customers & CRM',
    specSectionId: '10',
    status: 'built',
    metaTitle: 'Customers & CRM | Automatic Customer Profiles & Order History',
    metaDescription: 'Every DM automatically saves a customer profile, order history, and re-engagement tags.',
    h1: 'Every chat becomes a customer you can keep.',
    sub: 'Kasi saves who they are, what they bought, and where they are in the buying journey. Your customer list builds itself while you sell.',
  },
  FEATURE_ANALYTICS: {
    path: '/features/analytics',
    name: 'Analytics & Bookings',
    specSectionId: '11',
    status: 'built',
    metaTitle: 'Analytics & Bookings | Actionable Revenue & Appointment Metrics',
    metaDescription: 'Clear sales charts, inventory metrics, and automated appointment scheduling.',
    h1: 'Know what\'s selling. Book what\'s next.',
    sub: 'Kasi turns your chats and orders into clear numbers, and handles bookings for services, so a salon, a clinic, or a studio runs on the same system as a store.',
  },
  PLATFORMS: {
    path: '/platforms',
    name: 'Platforms & Integrations',
    specSectionId: '12',
    status: 'built',
    metaTitle: 'Platforms & Integrations | WhatsApp, Instagram, Messenger & Telegram',
    metaDescription: 'Connect WhatsApp, Instagram DMs, Facebook Messenger, and Telegram to a unified commerce engine.',
    h1: 'Wherever your customers message you, Kasi is already there.',
    sub: 'One brain, every channel. Your customers keep using the apps they know. You run it all from one place.',
  },
  TRY: {
    path: '/try',
    name: 'Try it',
    specSectionId: '13',
    status: 'stub',
    metaTitle: 'Try Kasi Yourself | Interactive Customer Experience Demo',
    metaDescription: 'Test Kasi in real-time as a buyer on WhatsApp and see how smoothly it sells.',
    h1: 'Experience Kasi as a customer right now.',
    sub: 'Chat with our live demo store on WhatsApp and see how quickly Kasi answers, negotiates, and checks out.',
    isNav: true,
  },
  MARKET: {
    path: '/market',
    name: 'Market',
    specSectionId: '14',
    status: 'built',
    metaTitle: 'Kasi Market | Discover & Buy from Local Nigerian Retailers',
    metaDescription: 'Shop verified local vendors directly on WhatsApp.',
    h1: 'Shop directly with top social commerce vendors.',
    sub: 'Kasi Market connects you directly with verified sellers.',
    isNav: true,
  },
  PRICING: {
    path: '/pricing',
    name: 'Pricing',
    specSectionId: '15',
    status: 'stub',
    metaTitle: 'Pricing | Simple Flat Monthly Plans for Social Commerce Sellers',
    metaDescription: 'Transparent pricing with no commissions on your sales. Starting from ₦18,000/month.',
    h1: 'Simple, transparent pricing for growing sellers.',
    sub: 'No hidden cuts. Keep 100% of your sales with flat monthly plans built for Nigerian SMEs.',
    isNav: true,
  },
  ABOUT: {
    path: '/about',
    name: 'About Endogenous',
    specSectionId: '16',
    status: 'stub',
    metaTitle: 'About Endogenous Tech | Building Africa’s Social Commerce OS',
    metaDescription: 'Learn about our mission to power the millions of merchants running on social DMs.',
    h1: 'We build technology for the merchants running Africa’s social economy.',
    sub: 'Endogenous Technologies empowers informal and growing retailers with autonomous sales infrastructure.',
  },
  BLOG: {
    path: 'https://blog.usekasi.com',
    name: 'Blog',
    specSectionId: '17',
    status: 'external',
    metaTitle: 'Kasi Blog | Playbooks & Guides for Social Sellers',
    metaDescription: 'Strategies, product updates, and growth stories for social commerce merchants.',
    h1: 'Playbooks and insights for social commerce.',
    sub: 'Tactics and stories from the fastest-growing stores on WhatsApp and Instagram.',
  },
  CONTACT: {
    path: '/contact',
    name: 'Contact',
    specSectionId: '18',
    status: 'stub',
    metaTitle: 'Contact Kasi | Talk to Our Sales & Support Team in Lagos',
    metaDescription: 'Get in touch with our engineering and growth team in Lagos, Nigeria.',
    h1: 'Let’s talk about growing your social sales.',
    sub: 'Our team in Lagos is ready to help you set up Kasi, connect your channels, and train your AI rep.',
  },
  GET_STARTED: {
    path: '/get-started',
    name: 'Get Started',
    specSectionId: '01',
    status: 'built',
    metaTitle: 'Get Started with Kasi | Free Account Setup',
    metaDescription: 'Sign up in two minutes and connect your WhatsApp store.',
    h1: 'Start selling autonomously today.',
    sub: 'Connect your store and start answering every message in seconds.',
  },
  DEV_LOGOS: {
    path: '/dev/logos',
    name: 'Vector Assets Dev Tool',
    status: 'built',
    metaTitle: 'Dev: Logo Assets Inspector',
    metaDescription: 'Verified vector inspection route for internal development.',
    h1: 'Verified Vector Assets Test Suite',
    sub: 'Internal inspector for brand and partner SVGs.',
  },
  DEV_TYPE: {
    path: '/dev/type',
    name: 'Typography Inspector',
    status: 'built',
    metaTitle: 'Dev: Typography Inspector',
    metaDescription: 'Side-by-side font comparison of Bricolage Grotesque vs Poppins.',
    h1: 'Typography Comparison',
    sub: 'Display font inspector for section headings.',
  },
};
